### ISSUE TITLE
test.py fails with recent main branch code.

### ISSUE THREAD

**Issue by suthaz** [gnana70/tamil_ocr#61]
Traceback (most recent call last):
  File "/Users/xx/PycharmProjects/tamil_ocr/test.py", line 9, in <module>
    text_list = ocr.predict(image_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/PycharmProjects/tamil_ocr/ocr_tamil/ocr.py", line 556, in predict
    exported_regions,updated_prediction_result = self.craft_detect(image)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/PycharmProjects/tamil_ocr/ocr_tamil/ocr.py", line 324, in craft_detect
    exported_file_paths = export_detected_regions(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: export_detected_regions() got an unexpected keyword argument 'method'

**Comment by gnana70** [comment]
@suthaz , Thanks for reporting the issue, this issue has been addressed now.
